export default {
  FIELDS_REQUIRED: 'FIELDS_REQUIRED',
  MESSAGE_REQUIRED: 'MESSAGE_REQUIRED',
  CONTEXT_REQUIRED: 'CONTEXT_REQUIRED',
  NOT_UNIQUE: 'NOT_UNIQUE',
  NOT_FOUND: 'NOT_FOUND',
  FORMAT_ERROR: 'FORMAT_ERROR',
};
