export default {
  FIELDS_REQUIRED: 'FIELDS_REQUIRED',
  MESSAGE_REQUIRED: 'MESSAGE_REQUIRED',
  CONTEXT_REQUIRED: 'CONTEXT_REQUIRED',
  SERVER_ERROR: 'SERVER_ERROR',
  NOT_UNIQUE: 'NOT_UNIQUE',
  NOT_FOUND: 'NOT_FOUND',
  FORMAT_ERROR: 'FORMAT_ERROR',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  EMAIL_OR_PASSWORD_NOT_CORRECT: 'EMAIL_OR_PASSWORD_NOT_CORRECT',
};
